### ISSUE TITLE
HWRF on Hera todo

### ISSUE THREAD

**Issue by jimfrimel** [jimfrimel/jfHWRF#12]
**Just keeping track of some HWRF Hera TODO items.**
----------
These are not critical and may/may not be addressed.
Feel free to add to this list.

**REMAINING**
Cores Socket / Node 20 / 40 (2.4GHz)
Memory 96GB / 384GB

These were discussed with the HWRF core and are not critical.
They may/may not be immediately addressed.
- [ ] Hera Nodes/Processor tuning
- [ ] hwrf_v4.0a_release.conf, Update ?
- [ ] Needs updating for Hera architecture.
        * forecast_procs.ent
        * forecast_procs.py
- [ ] Needs updating for Hera architecture.
        * ms_forecast_procs.ent
